export const questions = [
    {
        id: 1,
        question:
            'What is the correct syntax to print a message in the console in JavaScript?',
        options: [
            "print('Hello, World!')",
            "console.print('Hello, World!')",
            "console.log('Hello, World!')",
            "log.console('Hello, World!')",
        ],
        correctAnswer: 2,
        category: 'mcq',
    },
    {
        id: 2,
        question: 'Which of the following is a JavaScript data type?',
        options: ['Number', 'String', 'Boolean', 'All of the above'],
        correctAnswer: 3,
        category: 'mcq',
    },
    {
        id: 3,
        question: 'Which company developed JavaScript?',
        options: ['Mozilla', 'Netscape', 'Microsoft', 'Sun Microsystems'],
        correctAnswer: 1,
        category: 'mcq',
    },
    {
        id: 4,
        question: 'How do you create a function in JavaScript?',
        options: [
            'function myFunction() {}',
            'function:myFunction() {}',
            'function = myFunction() {}',
            'def myFunction() {}',
        ],
        correctAnswer: 0,
        category: 'mcq',
    },
    {
        id: 5,
        question:
            "How do you call a function named 'myFunction' in JavaScript?",
        options: [
            'call myFunction()',
            'call function myFunction()',
            'myFunction()',
            'Call.myFunction()',
        ],
        correctAnswer: 2,
        category: 'mcq',
    },
    {
        id: 6,
        question: 'Which event occurs when the user clicks on an HTML element?',
        options: ['onchange', 'onclick', 'onmouseover', 'onmouseclick'],
        correctAnswer: 1,
        category: 'mcq',
    },
    {
        id: 7,
        question: 'What is the correct way to write a JavaScript array?',
        options: [
            "var colors = 1 = ('red'), 2 = ('green'), 3 = ('blue')",
            "var colors = (1:'red', 2:'green', 3:'blue')",
            "var colors = ['red', 'green', 'blue']",
            "var colors = 'red', 'green', 'blue'",
        ],
        correctAnswer: 2,
        category: 'mcq',
    },
    {
        id: 8,
        question: 'How do you add a comment in JavaScript?',
        options: [
            "'This is a comment",
            '// This is a comment',
            '<!-- This is a comment -->',
            '/* This is a comment */',
        ],
        correctAnswer: 1,
        category: 'mcq',
    },
    {
        id: 9,
        question: 'What is the correct way to write a JavaScript object?',
        options: [
            "var person = {firstName:'John', lastName:'Doe'}",
            "var person = (firstName:'John', lastName:'Doe')",
            "var person = [firstName:'John', lastName:'Doe']",
            "var person = 'firstName':'John', 'lastName':'Doe'",
        ],
        correctAnswer: 0,
        category: 'mcq',
    },
    {
        id: 10,
        question: 'How do you declare a JavaScript variable?',
        options: [
            'var carName;',
            'variable carName;',
            'v carName;',
            'declare carName;',
        ],
        correctAnswer: 0,
        category: 'mcq',
    },
    {
        id: 11,
        question: 'Which operator is used to assign a value to a variable?',
        options: ['*', '-', '=', '+'],
        correctAnswer: 2,
        category: 'mcq',
    },
    {
        id: 12,
        question: 'What will the following code return: Boolean(10 > 9)?',
        options: ['true', 'false', 'NaN', 'undefined'],
        correctAnswer: 0,
        category: 'mcq',
    },
    {
        id: 13,
        question: 'What is the correct file extension for JavaScript files?',
        options: ['.js', '.java', '.javascript', '.jvs'],
        correctAnswer: 0,
        category: 'mcq',
    },
    {
        id: 14,
        question: 'How do you create a Date object in JavaScript?',
        options: [
            'new Date()',
            'Date()',
            'new Date(dateString)',
            'Both A and C',
        ],
        correctAnswer: 3,
        category: 'mcq',
    },
    {
        id: 15,
        question: 'How do you round the number 7.25 to the nearest integer?',
        options: [
            'Math.round(7.25)',
            'round(7.25)',
            'Math.rnd(7.25)',
            'rnd(7.25)',
        ],
        correctAnswer: 0,
        category: 'mcq',
    },
    {
        id: 16,
        question: 'Which method converts JSON data to a JavaScript object?',
        options: [
            'JSON.parse()',
            'JSON.stringify()',
            'JSON.convert()',
            'JSON.objectify()',
        ],
        correctAnswer: 0,
        category: 'mcq',
    },
    {
        id: 17,
        question:
            'Which method is used to add an element at the end of an array?',
        options: ['push()', 'pop()', 'shift()', 'unshift()'],
        correctAnswer: 0,
        category: 'mcq',
    },
    {
        id: 18,
        question:
            "How do you write a conditional statement for executing some code if 'i' is NOT equal to 5?",
        options: ['if (i <> 5)', 'if i <> 5', 'if (i != 5)', 'if i =! 5 then'],
        correctAnswer: 2,
        category: 'mcq',
    },
    {
        id: 19,
        question: 'Which method removes the last element from an array?',
        options: ['pop()', 'remove()', 'slice()', 'shift()'],
        correctAnswer: 0,
        category: 'mcq',
    },
    {
        id: 20,
        question: 'Which method can be used to join two or more arrays?',
        options: ['concat()', 'merge()', 'join()', 'combine()'],
        correctAnswer: 0,
        category: 'mcq',
    },
    {
        id: 21,
        question: 'Which keyword is used to declare a constant in JavaScript?',
        options: ['const', 'let', 'var', 'constant'],
        correctAnswer: 0,
        category: 'mcq',
    },
    {
        id: 22,
        question: "What is the output of 'typeof NaN'?",
        options: ["'number'", "'NaN'", "'undefined'", "'object'"],
        correctAnswer: 0,
        category: 'mcq',
    },
    {
        id: 23,
        question: 'How do you write a JavaScript object literal?',
        options: [
            "{ name: 'John', age: 30 }",
            "{ name = 'John', age = 30 }",
            "[ name: 'John', age: 30 ]",
            "( name: 'John', age: 30 )",
        ],
        correctAnswer: 0,
        category: 'mcq',
    },
    {
        id: 24,
        question: 'Which method can be used to find the length of a string?',
        options: ['length()', 'size()', 'len()', 'None of the above'],
        correctAnswer: 3,
        category: 'mcq',
    },
    {
        id: 25,
        question: 'How do you define a class in JavaScript?',
        options: [
            'class MyClass {}',
            'function MyClass() {}',
            'class: MyClass {}',
            'def MyClass() {}',
        ],
        correctAnswer: 0,
        category: 'mcq',
    },
    {
        id: 26,
        question: 'two-sum',
        category: 'code',
    },
    {
        id: 27,
        question: 'plus-one',
        category: 'code',
    },
];
